@startuml
skinparam classAttributeIconSize 0

package "도메인 모델" {

class 유저 {
  - 유저ID: UUID
  - 잔액: int
  + 충전(금액: int)
  + 차감(금액: int)
}

class 대기열토큰 {
  - 토큰ID: String
  - 유저ID: UUID
  - 대기순번: int
  - 발급시각: DateTime
  + 유효한가(): boolean
}

class 예약 {
  - 예약ID: UUID
  - 유저ID: UUID
  - 예약일자: 날짜
  - 좌석목록: List<좌석>
  - 상태: 예약상태
  + 만료여부확인(): boolean
}

class 좌석 {
  - 좌석번호: int
  - 상태: 좌석상태
  - 임시예약종료시각: DateTime
}

class 결제 {
  - 결제ID: UUID
  - 예약ID: UUID
  - 결제금액: int
  - 결제시각: DateTime
}

enum 예약상태 {
  임시
  확정
  만료됨
}

enum 좌석상태 {
  사용가능
  임시예약중
  예약완료
}

유저 "1" -- "0..*" 대기열토큰
유저 "1" -- "0..*" 예약
예약 "1" -- "1..4" 좌석
예약 "1" -- "0..1" 결제

}
@enduml