@startuml
skinparam componentStyle rectangle

package "콘서트 예약 시스템" {

  [유저] as 유저
  [대기열] as 대기열
  [예약] as 예약
  [결제] as 결제
  [잔액] as 잔액
  [좌석 락] as 락
}

유저 --> 대기열 : 사용
대기열 --> 예약 : 파트너 관계
예약 --> 락 : 상태 공유 (Shared Kernel)
예약 --> 결제 : 종속 (Conformist)
결제 --> 잔액 : 고객 (Customer)
유저 --> 잔액 : 사용

@enduml